server:
  port: 8088

mybatis:
  type-aliases-package: com.jn.audit.examples.springmvcdemo.common.model
  mapper-locations: classpath*:mapper/*.xml

sqlhelper:
  dynamic-datasource:
    enabled: true
  mybatis:
    instrumentor:
      name: mybatis
      cache-instrumented-sql: true
      subquery-paging-start-flag: "[PAGING_START]"
      subquery-paging-end-flag: "[PAGING_END]"
spring:
  datasource:
    url: jdbc:h2:file:${user.dir}/audit-examples/audit-examples-springmvcdemo/src/main/resources/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456

logging:
  level:
    root: info
    com:
      jn:
        sqlhelper:
          examples:
            common:
              dao: trace

operation:
  definition:
    location: classpath:/operation.yml
    reload-interval-in-seconds: -1
audit:
  enabled: true
  async-mode: false
  topics: [DEFAULT, LOGIN_LOGOUT]
  topic-configs:
    - name: DEFAULT
      ring-buffer-size: 1024
      producer-type: MULTI
    - name: LOGIN_LOGOUT
      ring-buffer-size: 512
      producer-type: SINGLE
  http-interceptor-patterns:
    - /consumers/**
    - /users/**
  advisor-pointcut:
    expression: execution(public * com.jn.audit.examples.springmvcdemo.common.controller.*Controller.*(..))

agileway:
  web:
    streamWrapper: ${audit.enabled}